### ISSUE TITLE
hello message

### ISSUE THREAD

**Issue by cricket1100** [UTKARSH67777BABABAB/BLA#1]
hello contributing in this

**Comment by UTKARSH67777BABABAB** [comment]
SURE

**Comment by cricket1100** [comment]
ok

**Comment by cricket1100** [comment]
uttkarsh pull request

**Comment by cricket1100** [comment]
did you get anything in pull request?
you can ask doubts here

**Comment by cricket1100** [comment]
now what we should do is create a new branch in git and then write our code.
so we will be creting it like this the work which we did in visual code we are copying and pasting here in different branches we can directly create a new editing file though but that's wastage of our vs code work so we are doing this did you understand?

**Comment by cricket1100** [comment]
`*{
    margin: 0;
    padding:0;
}
marquee{
    font-size: 22px;
    font-style: oblique;
    font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;
    font-stretch: normal;
    box-sizing: border-box;
    text-align: center;
}`

**Comment by cricket1100** [comment]
> `*{ margin: 0; padding:0; } marquee{ font-size: 22px; font-style: oblique; font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif; font-stretch: normal; box-sizing: border-box; text-align: center; }`
